project:
  type: book
  output-dir: docs
  # preview: 
  #   port: 4200
  #   browser: true

execute:
  freeze: true  # re-render only when source changes
  cache: true
  warning: false

book:
  title: "TDA Workshop - EBT 2024"
  reader-mode: true
  # subtitle: "With examples in Julia"
  # site-url: https://juliatda.github.io/MetricSpaces.jl/
  # repo-url: https://github.com/juliatda/MetricSpaces.jl
  author: "G. Vituri"
  # date: "2024-03-22"
  # sharing: [twitter, linkedin]
  # downloads: [pdf, epub]

  chapters:
    - index.qmd
    - introduction.qmd
    - part: "Part 1: Persistence homology"
      chapters:
      - "getting started.qmd"
      - 3d-shapes.qmd
      - digits.qmd
      - wings.qmd
    - part: "Part 2: Mapper"
      chapters:
      - "mapper.qmd"
    - references.qmd

format:
  html:
    # theme: flatly
    theme: flatly
    # css: style.css    
    code-link: true
    page-layout: full
    max-width: 90vw
    preview-links: true
    # code-fold: true
    toc-depth: 4
    number-depth: 3
    toc-expand: true
    code-tools: true
    grid:
      sidebar-width: 300px
      body-width: 1200px

bibliography: references.bib

# engine: julia

jupyter: julia-1.10

  # pdf:
  #   documentclass: scrreprt